/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as MasculinoRouteImport } from './routes/masculino'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfantilRouteImport } from './routes/infantil'
import { Route as FemininoRouteImport } from './routes/feminino'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoupasIndexRouteImport } from './routes/roupas.index'
import { Route as MarcasIndexRouteImport } from './routes/marcas.index'
import { Route as RoupasCategoryRouteImport } from './routes/roupas.$category'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as MarcasBrandRouteImport } from './routes/marcas.$brand'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MasculinoRoute = MasculinoRouteImport.update({
  id: '/masculino',
  path: '/masculino',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfantilRoute = InfantilRouteImport.update({
  id: '/infantil',
  path: '/infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const FemininoRoute = FemininoRouteImport.update({
  id: '/feminino',
  path: '/feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoupasIndexRoute = RoupasIndexRouteImport.update({
  id: '/roupas/',
  path: '/roupas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasIndexRoute = MarcasIndexRouteImport.update({
  id: '/marcas/',
  path: '/marcas/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoupasCategoryRoute = RoupasCategoryRouteImport.update({
  id: '/roupas/$category',
  path: '/roupas/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasBrandRoute = MarcasBrandRouteImport.update({
  id: '/marcas/$brand',
  path: '/marcas/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/login': typeof LoginRoute
  '/masculino': typeof MasculinoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/ofertas': typeof OfertasRoute
  '/marcas/$brand': typeof MarcasBrandRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/roupas/$category': typeof RoupasCategoryRoute
  '/marcas/': typeof MarcasIndexRoute
  '/roupas/': typeof RoupasIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/login': typeof LoginRoute
  '/masculino': typeof MasculinoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/ofertas': typeof OfertasRoute
  '/marcas/$brand': typeof MarcasBrandRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/roupas/$category': typeof RoupasCategoryRoute
  '/marcas': typeof MarcasIndexRoute
  '/roupas': typeof RoupasIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/login': typeof LoginRoute
  '/masculino': typeof MasculinoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/ofertas': typeof OfertasRoute
  '/marcas/$brand': typeof MarcasBrandRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/roupas/$category': typeof RoupasCategoryRoute
  '/marcas/': typeof MarcasIndexRoute
  '/roupas/': typeof RoupasIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/feminino'
    | '/infantil'
    | '/login'
    | '/masculino'
    | '/minha-conta'
    | '/ofertas'
    | '/marcas/$brand'
    | '/produto/$id'
    | '/roupas/$category'
    | '/marcas/'
    | '/roupas/'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/feminino'
    | '/infantil'
    | '/login'
    | '/masculino'
    | '/minha-conta'
    | '/ofertas'
    | '/marcas/$brand'
    | '/produto/$id'
    | '/roupas/$category'
    | '/marcas'
    | '/roupas'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/feminino'
    | '/infantil'
    | '/login'
    | '/masculino'
    | '/minha-conta'
    | '/ofertas'
    | '/marcas/$brand'
    | '/produto/$id'
    | '/roupas/$category'
    | '/marcas/'
    | '/roupas/'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  FemininoRoute: typeof FemininoRoute
  InfantilRoute: typeof InfantilRoute
  LoginRoute: typeof LoginRoute
  MasculinoRoute: typeof MasculinoRoute
  MinhaContaRoute: typeof MinhaContaRoute
  OfertasRoute: typeof OfertasRoute
  MarcasBrandRoute: typeof MarcasBrandRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  RoupasCategoryRoute: typeof RoupasCategoryRoute
  MarcasIndexRoute: typeof MarcasIndexRoute
  RoupasIndexRoute: typeof RoupasIndexRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masculino': {
      id: '/masculino'
      path: '/masculino'
      fullPath: '/masculino'
      preLoaderRoute: typeof MasculinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infantil': {
      id: '/infantil'
      path: '/infantil'
      fullPath: '/infantil'
      preLoaderRoute: typeof InfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feminino': {
      id: '/feminino'
      path: '/feminino'
      fullPath: '/feminino'
      preLoaderRoute: typeof FemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roupas/': {
      id: '/roupas/'
      path: '/roupas'
      fullPath: '/roupas/'
      preLoaderRoute: typeof RoupasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/': {
      id: '/marcas/'
      path: '/marcas'
      fullPath: '/marcas/'
      preLoaderRoute: typeof MarcasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roupas/$category': {
      id: '/roupas/$category'
      path: '/roupas/$category'
      fullPath: '/roupas/$category'
      preLoaderRoute: typeof RoupasCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/$brand': {
      id: '/marcas/$brand'
      path: '/marcas/$brand'
      fullPath: '/marcas/$brand'
      preLoaderRoute: typeof MarcasBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  FemininoRoute: FemininoRoute,
  InfantilRoute: InfantilRoute,
  LoginRoute: LoginRoute,
  MasculinoRoute: MasculinoRoute,
  MinhaContaRoute: MinhaContaRoute,
  OfertasRoute: OfertasRoute,
  MarcasBrandRoute: MarcasBrandRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  RoupasCategoryRoute: RoupasCategoryRoute,
  MarcasIndexRoute: MarcasIndexRoute,
  RoupasIndexRoute: RoupasIndexRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
