/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as MasculinoRouteImport } from './routes/masculino'
import { Route as MaisVendidosRouteImport } from './routes/mais-vendidos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as KitValidadorRouteImport } from './routes/kit-validador'
import { Route as InfantilRouteImport } from './routes/infantil'
import { Route as FemininoRouteImport } from './routes/feminino'
import { Route as DestaquesRouteImport } from './routes/destaques'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as MaxorcrmRouteRouteImport } from './routes/maxorcrm/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoupasIndexRouteImport } from './routes/roupas.index'
import { Route as MaxorcrmIndexRouteImport } from './routes/maxorcrm/index'
import { Route as MarcasIndexRouteImport } from './routes/marcas.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RoupasCategoryRouteImport } from './routes/roupas.$category'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as MarcasBrandRouteImport } from './routes/marcas.$brand'
import { Route as ColecaoMasculinoRouteImport } from './routes/colecao.masculino'
import { Route as ColecaoFemininoRouteImport } from './routes/colecao.feminino'
import { Route as BlogGuiaTenisNikeRouteImport } from './routes/blog.guia-tenis-nike'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicCrmProductsRouteImport } from './routes/api/public/crm/products'
import { Route as ApiPublicCrmImageSplatRouteImport } from './routes/api/public/crm/image.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const MasculinoRoute = MasculinoRouteImport.update({
  id: '/masculino',
  path: '/masculino',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisVendidosRoute = MaisVendidosRouteImport.update({
  id: '/mais-vendidos',
  path: '/mais-vendidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const KitValidadorRoute = KitValidadorRouteImport.update({
  id: '/kit-validador',
  path: '/kit-validador',
  getParentRoute: () => rootRouteImport,
} as any)
const InfantilRoute = InfantilRouteImport.update({
  id: '/infantil',
  path: '/infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const FemininoRoute = FemininoRouteImport.update({
  id: '/feminino',
  path: '/feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const DestaquesRoute = DestaquesRouteImport.update({
  id: '/destaques',
  path: '/destaques',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxorcrmRouteRoute = MaxorcrmRouteRouteImport.update({
  id: '/maxorcrm',
  path: '/maxorcrm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoupasIndexRoute = RoupasIndexRouteImport.update({
  id: '/roupas/',
  path: '/roupas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxorcrmIndexRoute = MaxorcrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaxorcrmRouteRoute,
} as any)
const MarcasIndexRoute = MarcasIndexRouteImport.update({
  id: '/marcas/',
  path: '/marcas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoupasCategoryRoute = RoupasCategoryRouteImport.update({
  id: '/roupas/$category',
  path: '/roupas/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasBrandRoute = MarcasBrandRouteImport.update({
  id: '/marcas/$brand',
  path: '/marcas/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoMasculinoRoute = ColecaoMasculinoRouteImport.update({
  id: '/colecao/masculino',
  path: '/colecao/masculino',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoFemininoRoute = ColecaoFemininoRouteImport.update({
  id: '/colecao/feminino',
  path: '/colecao/feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogGuiaTenisNikeRoute = BlogGuiaTenisNikeRouteImport.update({
  id: '/blog/guia-tenis-nike',
  path: '/blog/guia-tenis-nike',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmProductsRoute = ApiPublicCrmProductsRouteImport.update({
  id: '/api/public/crm/products',
  path: '/api/public/crm/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmImageSplatRoute = ApiPublicCrmImageSplatRouteImport.update({
  id: '/api/public/crm/image/$',
  path: '/api/public/crm/image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maxorcrm': typeof MaxorcrmRouteRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/destaques': typeof DestaquesRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/kit-validador': typeof KitValidadorRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/mais-vendidos': typeof MaisVendidosRoute
  '/masculino': typeof MasculinoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/ofertas': typeof OfertasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRoute
  '/blog/guia-tenis-nike': typeof BlogGuiaTenisNikeRoute
  '/colecao/feminino': typeof ColecaoFemininoRoute
  '/colecao/masculino': typeof ColecaoMasculinoRoute
  '/marcas/$brand': typeof MarcasBrandRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/roupas/$category': typeof RoupasCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/marcas/': typeof MarcasIndexRoute
  '/maxorcrm/': typeof MaxorcrmIndexRoute
  '/roupas/': typeof RoupasIndexRoute
  '/api/public/crm/products': typeof ApiPublicCrmProductsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/api/public/crm/image/$': typeof ApiPublicCrmImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/destaques': typeof DestaquesRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/kit-validador': typeof KitValidadorRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/mais-vendidos': typeof MaisVendidosRoute
  '/masculino': typeof MasculinoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/ofertas': typeof OfertasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRoute
  '/blog/guia-tenis-nike': typeof BlogGuiaTenisNikeRoute
  '/colecao/feminino': typeof ColecaoFemininoRoute
  '/colecao/masculino': typeof ColecaoMasculinoRoute
  '/marcas/$brand': typeof MarcasBrandRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/roupas/$category': typeof RoupasCategoryRoute
  '/admin': typeof AdminIndexRoute
  '/marcas': typeof MarcasIndexRoute
  '/maxorcrm': typeof MaxorcrmIndexRoute
  '/roupas': typeof RoupasIndexRoute
  '/api/public/crm/products': typeof ApiPublicCrmProductsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/api/public/crm/image/$': typeof ApiPublicCrmImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maxorcrm': typeof MaxorcrmRouteRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/destaques': typeof DestaquesRoute
  '/feminino': typeof FemininoRoute
  '/infantil': typeof InfantilRoute
  '/kit-validador': typeof KitValidadorRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/mais-vendidos': typeof MaisVendidosRoute
  '/masculino': typeof MasculinoRoute
  '/minha-conta': typeof MinhaContaRoute
  '/ofertas': typeof OfertasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/crm': typeof AdminCrmRoute
  '/blog/guia-tenis-nike': typeof BlogGuiaTenisNikeRoute
  '/colecao/feminino': typeof ColecaoFemininoRoute
  '/colecao/masculino': typeof ColecaoMasculinoRoute
  '/marcas/$brand': typeof MarcasBrandRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/roupas/$category': typeof RoupasCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/marcas/': typeof MarcasIndexRoute
  '/maxorcrm/': typeof MaxorcrmIndexRoute
  '/roupas/': typeof RoupasIndexRoute
  '/api/public/crm/products': typeof ApiPublicCrmProductsRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
  '/api/public/crm/image/$': typeof ApiPublicCrmImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maxorcrm'
    | '/catalogo'
    | '/categorias'
    | '/checkout'
    | '/destaques'
    | '/feminino'
    | '/infantil'
    | '/kit-validador'
    | '/lancamentos'
    | '/login'
    | '/mais-vendidos'
    | '/masculino'
    | '/minha-conta'
    | '/ofertas'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/blog/guia-tenis-nike'
    | '/colecao/feminino'
    | '/colecao/masculino'
    | '/marcas/$brand'
    | '/produto/$id'
    | '/roupas/$category'
    | '/admin/'
    | '/marcas/'
    | '/maxorcrm/'
    | '/roupas/'
    | '/api/public/crm/products'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp'
    | '/api/public/crm/image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/categorias'
    | '/checkout'
    | '/destaques'
    | '/feminino'
    | '/infantil'
    | '/kit-validador'
    | '/lancamentos'
    | '/login'
    | '/mais-vendidos'
    | '/masculino'
    | '/minha-conta'
    | '/ofertas'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/blog/guia-tenis-nike'
    | '/colecao/feminino'
    | '/colecao/masculino'
    | '/marcas/$brand'
    | '/produto/$id'
    | '/roupas/$category'
    | '/admin'
    | '/marcas'
    | '/maxorcrm'
    | '/roupas'
    | '/api/public/crm/products'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp'
    | '/api/public/crm/image/$'
  id:
    | '__root__'
    | '/'
    | '/maxorcrm'
    | '/catalogo'
    | '/categorias'
    | '/checkout'
    | '/destaques'
    | '/feminino'
    | '/infantil'
    | '/kit-validador'
    | '/lancamentos'
    | '/login'
    | '/mais-vendidos'
    | '/masculino'
    | '/minha-conta'
    | '/ofertas'
    | '/sitemap.xml'
    | '/admin/crm'
    | '/blog/guia-tenis-nike'
    | '/colecao/feminino'
    | '/colecao/masculino'
    | '/marcas/$brand'
    | '/produto/$id'
    | '/roupas/$category'
    | '/admin/'
    | '/marcas/'
    | '/maxorcrm/'
    | '/roupas/'
    | '/api/public/crm/products'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/whatsapp'
    | '/api/public/crm/image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaxorcrmRouteRoute: typeof MaxorcrmRouteRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  CategoriasRoute: typeof CategoriasRoute
  CheckoutRoute: typeof CheckoutRoute
  DestaquesRoute: typeof DestaquesRoute
  FemininoRoute: typeof FemininoRoute
  InfantilRoute: typeof InfantilRoute
  KitValidadorRoute: typeof KitValidadorRoute
  LancamentosRoute: typeof LancamentosRoute
  LoginRoute: typeof LoginRoute
  MaisVendidosRoute: typeof MaisVendidosRoute
  MasculinoRoute: typeof MasculinoRoute
  MinhaContaRoute: typeof MinhaContaRoute
  OfertasRoute: typeof OfertasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCrmRoute: typeof AdminCrmRoute
  BlogGuiaTenisNikeRoute: typeof BlogGuiaTenisNikeRoute
  ColecaoFemininoRoute: typeof ColecaoFemininoRoute
  ColecaoMasculinoRoute: typeof ColecaoMasculinoRoute
  MarcasBrandRoute: typeof MarcasBrandRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  RoupasCategoryRoute: typeof RoupasCategoryRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MarcasIndexRoute: typeof MarcasIndexRoute
  RoupasIndexRoute: typeof RoupasIndexRoute
  ApiPublicCrmProductsRoute: typeof ApiPublicCrmProductsRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
  ApiPublicCrmImageSplatRoute: typeof ApiPublicCrmImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masculino': {
      id: '/masculino'
      path: '/masculino'
      fullPath: '/masculino'
      preLoaderRoute: typeof MasculinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais-vendidos': {
      id: '/mais-vendidos'
      path: '/mais-vendidos'
      fullPath: '/mais-vendidos'
      preLoaderRoute: typeof MaisVendidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit-validador': {
      id: '/kit-validador'
      path: '/kit-validador'
      fullPath: '/kit-validador'
      preLoaderRoute: typeof KitValidadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infantil': {
      id: '/infantil'
      path: '/infantil'
      fullPath: '/infantil'
      preLoaderRoute: typeof InfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feminino': {
      id: '/feminino'
      path: '/feminino'
      fullPath: '/feminino'
      preLoaderRoute: typeof FemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destaques': {
      id: '/destaques'
      path: '/destaques'
      fullPath: '/destaques'
      preLoaderRoute: typeof DestaquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maxorcrm': {
      id: '/maxorcrm'
      path: '/maxorcrm'
      fullPath: '/maxorcrm'
      preLoaderRoute: typeof MaxorcrmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roupas/': {
      id: '/roupas/'
      path: '/roupas'
      fullPath: '/roupas/'
      preLoaderRoute: typeof RoupasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maxorcrm/': {
      id: '/maxorcrm/'
      path: '/'
      fullPath: '/maxorcrm/'
      preLoaderRoute: typeof MaxorcrmIndexRouteImport
      parentRoute: typeof MaxorcrmRouteRoute
    }
    '/marcas/': {
      id: '/marcas/'
      path: '/marcas'
      fullPath: '/marcas/'
      preLoaderRoute: typeof MarcasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roupas/$category': {
      id: '/roupas/$category'
      path: '/roupas/$category'
      fullPath: '/roupas/$category'
      preLoaderRoute: typeof RoupasCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas/$brand': {
      id: '/marcas/$brand'
      path: '/marcas/$brand'
      fullPath: '/marcas/$brand'
      preLoaderRoute: typeof MarcasBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/masculino': {
      id: '/colecao/masculino'
      path: '/colecao/masculino'
      fullPath: '/colecao/masculino'
      preLoaderRoute: typeof ColecaoMasculinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/feminino': {
      id: '/colecao/feminino'
      path: '/colecao/feminino'
      fullPath: '/colecao/feminino'
      preLoaderRoute: typeof ColecaoFemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/guia-tenis-nike': {
      id: '/blog/guia-tenis-nike'
      path: '/blog/guia-tenis-nike'
      fullPath: '/blog/guia-tenis-nike'
      preLoaderRoute: typeof BlogGuiaTenisNikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/products': {
      id: '/api/public/crm/products'
      path: '/api/public/crm/products'
      fullPath: '/api/public/crm/products'
      preLoaderRoute: typeof ApiPublicCrmProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/image/$': {
      id: '/api/public/crm/image/$'
      path: '/api/public/crm/image/$'
      fullPath: '/api/public/crm/image/$'
      preLoaderRoute: typeof ApiPublicCrmImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MaxorcrmRouteRouteChildren {
  MaxorcrmIndexRoute: typeof MaxorcrmIndexRoute
}

const MaxorcrmRouteRouteChildren: MaxorcrmRouteRouteChildren = {
  MaxorcrmIndexRoute: MaxorcrmIndexRoute,
}

const MaxorcrmRouteRouteWithChildren = MaxorcrmRouteRoute._addFileChildren(
  MaxorcrmRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaxorcrmRouteRoute: MaxorcrmRouteRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  CategoriasRoute: CategoriasRoute,
  CheckoutRoute: CheckoutRoute,
  DestaquesRoute: DestaquesRoute,
  FemininoRoute: FemininoRoute,
  InfantilRoute: InfantilRoute,
  KitValidadorRoute: KitValidadorRoute,
  LancamentosRoute: LancamentosRoute,
  LoginRoute: LoginRoute,
  MaisVendidosRoute: MaisVendidosRoute,
  MasculinoRoute: MasculinoRoute,
  MinhaContaRoute: MinhaContaRoute,
  OfertasRoute: OfertasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCrmRoute: AdminCrmRoute,
  BlogGuiaTenisNikeRoute: BlogGuiaTenisNikeRoute,
  ColecaoFemininoRoute: ColecaoFemininoRoute,
  ColecaoMasculinoRoute: ColecaoMasculinoRoute,
  MarcasBrandRoute: MarcasBrandRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  RoupasCategoryRoute: RoupasCategoryRoute,
  AdminIndexRoute: AdminIndexRoute,
  MarcasIndexRoute: MarcasIndexRoute,
  RoupasIndexRoute: RoupasIndexRoute,
  ApiPublicCrmProductsRoute: ApiPublicCrmProductsRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
  ApiPublicCrmImageSplatRoute: ApiPublicCrmImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
